name: build-windows-exe

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build (windowed, include conocimientos.md)
        shell: bash
        run: |
          # En Windows, PyInstaller usa ';' como separador de --add-data
          pyinstaller --noconfirm --onefile --windowed \
            --name CallCenterHelper \
            --add-data "conocimientos.md;." \
            app.py

      - name: Upload artifact (exe + conocimientos.md)
        uses: actions/upload-artifact@v4
        with:
          name: CallCenterHelper_build
          path: |
            dist/CallCenterHelper.exe
            conocimientos.md

