name: build-windows-onedir

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build (onedir, windowed, include conocimientos.md)
        run: |
          pyinstaller --noconfirm --onedir --windowed --name CallCenterHelper ^
            --collect-all PySide6 ^
            --collect-all qdarkstyle ^
            --add-data "conocimientos.md;." ^
            app.py

      - name: Zip onedir folder
        run: |
          powershell -command "Compress-Archive -Path 'dist\\CallCenterHelper\\*' -DestinationPath 'dist\\CallCenterHelper_onedir.zip'"

      - name: Upload artifact (onedir .zip)
        uses: actions/upload-artifact@v4
        with:
          name: CallCenterHelper_onedir
          path: dist/CallCenterHelper_onedir.zip

